chore(ci): Adiciona validação de manifestos para o ArgoCD Resolves #9

diff --git a/.github/workflows/manifest-validation.yaml b/.github/workflows/manifest-validation.yaml
--- a/.github/workflows/manifest-validation.yaml
+++ b/.github/workflows/manifest-validation.yaml
@@ -11,17 +11,29 @@ jobs:
 
             - name: Check dependencies
               env:
-                BINARY: yq_linux_amd64
-                VERSION: v4.47.1
+                YQ_BINARY: yq_linux_amd64
+                YQ_VERSION: v4.47.1
+                KUBECONFORM_VERSION: v0.7.0
+                ARGOCD_SCHEMA: schema/argocd/v3.0.9
               run: |
-                command -v yq --version &> /dev/null || (\
-                wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}.tar.gz -O - |\
-                tar xz && sudo mv ${BINARY} /usr/local/bin/yq
+                command -v yq &>/dev/null || (\
+                  echo "::notice title=Install yq"
+                  wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY}.tar.gz -O - |\
+                  tar xz && sudo mv ${BINARY} /usr/local/bin/yq
                 )
+
+                command -v kubeconform &>/dev/null || (\
+                  echo "::notice title=Install Kubeconform"
+                  go install github.com/yannh/kubeconform/cmd/kubeconform@${KUBECONFORM_VERSION}           
+                )
+
+                echo "::notice file=kubeconform,title=Set Kubeconform to path"
+
+                echo "PATH=${PATH}:${HOME}/go/bin" >> $GITHUB_ENV
 
             - name: Get changed manifests
               run: |
-                echo "CHANGED_FILES=$(git diff ${{ github.ref }}..main --name-only -- ./apps)" >> $GITHUB_ENV
+                echo "CHANGED_FILES=$(git diff main..${{ github.ref }} --name-only -- ./apps)" >> $GITHUB_ENV
           
             - name: Validate manifests
               run: |
@@ -33,25 +45,16 @@ jobs:
                 for manifest in "${CHANGED_FILES[@]}";
                 do
 
-                  if [ -f "${manifest}" ]; then
+                  if [ ! -f "${manifest}" ]; then
                     echo "::warning file=${manifest},title=NOT_FOUND::Manifest not found, skipping"
                     continue
                   fi
 
-                  if command -v yq &>/dev/null; then
-                    KIND=$(yq e '.kind' "${manifest}" 2>/dev/null)
-                  else
-                    KIND=$(grep -m1 '^kind' "${manifest}" | sed 's/kind:[[:space:]]*//')
-                  fi
-
                  echo "::notice file=${manifest},title=Validate::Manifest validation kind: ${KIND}"
-                 kubeconform -schema-location default -summary -verbose ${manifest}
+                 kubeconform -schema-location default -schema-location '${ARGOCD_SCHEMA}/v3.0.9/{{ .ResourceAPIVersion}}{{ .ResourceKind }},json' -summary -verbose ${manifest}
 
                  if [ $? -ne 0 ]; then
-                   echo "::error file=${manifest},title=Manifest validaiton failed for kind ${KIND}"
+                   echo "::error file=${manifest},title=Manifest validation failed for kind ${KIND}"
                    exit 1
                  fi
-                done
-
-                
-              
+                done            
