chore: Atualiza passo do workflow Resolves #9

diff --git a/.github/workflows/manifest-validation.yaml b/.github/workflows/manifest-validation.yaml
--- a/.github/workflows/manifest-validation.yaml
+++ b/.github/workflows/manifest-validation.yaml
@@ -16,6 +16,7 @@ jobs:
               uses: actions/checkout@v4
               with:
                 fetch-depth: 0
+                ref: ${{ github.event.pull_request.head.sha }}
 
             - name: Setup git references
               run: git remote set-head origin --auto
@@ -69,3 +70,24 @@ jobs:
                    exit 1
                  fi
                 done
+            - name: Store manifest validation report
+              uses: actions/upload-artifact@v4
+              with:
+                name: manifest-validation-result
+                path: test-results/TEST-*.txt
+                retention-days: 7
+    comment_on_pr:
+      runs-on: ubuntu-latest
+      steps:
+        - name: Get manifest validation report
+          uses: actions/download-artifact@v4
+          with:
+            name: manifest-validation-result
+
+        # - name: Comment on PR
+        #   if: success() || failure()
+        #   uses: git@100.87.222.25:homelab/actions.git/comment-on-pr@v0.1.0
+        #   with:
+        #     content: test-results/TEST-manifest-validation.txt
+        
+
